### ISSUE TITLE
Sync stuck on block 255861

### ISSUE THREAD

**Issue by Kafkamorph** [ac0v/burstcoin#13] opened 2017-08-28 06:44 UTC
> [SEVERE] 2017-08-28 07:43:20 nxt.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
java.lang.RuntimeException: java.sql.BatchUpdateException: (conn:90815) Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'name' at row 1
	at nxt.db.VersionedBatchEntityDbTable.finish(VersionedBatchEntityDbTable.java:82)
	at nxt.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:962)
	at nxt.BlockchainProcessorImpl.access$500(BlockchainProcessorImpl.java:33)
	at nxt.BlockchainProcessorImpl$3.run(BlockchainProcessorImpl.java:187)
	at nxt.util.ThreadPool.lambda$start$0(ThreadPool.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: (conn:90815) Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'name' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:296)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:290)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:125)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at nxt.db.VersionedBatchEntityDbTable.finish(VersionedBatchEntityDbTable.java:79)
	... 11 more
Caused by: java.sql.SQLException: (conn:90815) Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'name' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:179)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:293)
	... 15 more
Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'name' at row 1
Query is: REPLACE INTO account (id, creation_height, public_key, key_height, balance, unconfirmed_balance, forged_balance, name, description, height, latest) VALUES (-1281866337468114894, 248596, <bytearray:�F3�����&�O�9�~�'�X.g1<�V61>, 248615, 691088763164, 691088763164, 0, '🔥🔥🔥🔥 ( ͡° ͜ʖ ͡°) 🔥🔥🔥🔥', 'Burst YL Pt', 255861, TRUE)
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$1.handleResultException(AbstractQueryProtocol.java:307)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by michaelmattig** [comment] 2017-08-28 07:38
What version are you using? This should be fixed with 6c5c20537c23a678801b1e3ebd59432c7609f068

**Comment by T5-R** [comment] 2017-09-03 09:03
I have the same/simmilar issue. I downloaded the latest release.

    Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'name' at row 1
    Query is: REPLACE INTO account (id, creation_height, public_key, key_height, balance, unconfirmed_balance, forged_balance, name, description, height, latest) VALUES (-1281866337468114894, 248596, <bytearray:ÑF3×ÏâêÍ&óO†9â~?'–X.g1<?V61>, 248615, 691088763164, 691088763164, 0, '???? ( ?° ?? ?°) ????', 'Burst YL Pt', 255861, TRUE)

**Comment by ac0v** [comment] 2017-09-05 11:28
As of today, 1.3.4cg has been released - this version should fix your issue which is caused by some mysql/mariadb default settings which vary on different distributions
.
It is also available as debian/ubuntu package using https://package.cryptoguru.org

**Closed** 2017-09-05 12:56 UTC

**Comment by Kafkamorph** [comment] 2017-09-05 19:02
Confirm fixed. Good stuff. 👍
